// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wixngvknbvjthbasfijk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpeG5ndmtuYnZqdGhiYXNmaWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MjIxODIsImV4cCI6MjA1OTE5ODE4Mn0.BfK7Zn6adUbIeJNw1p2_iCCh-aex342SCbcgNluPPpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);